# Generated by Django 2.0.1 on 2018-01-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccTree',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('pID', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
